name: core-regression

on:
  push:
  pull_request:

jobs:
  node-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install --ignore-scripts
      - run: npm run test:stage8-2G-C-1
      - run: npm run test:stage8-2G-D-C-1-prep
      - run: npm run test:stage8-2G-D-C-1
      - run: npm run test:stage8-2G-C-1-1
      - run: npm run test:stage8-2G-C-1-1a
      - run: npm run test:stage8-2G-B-1-1a
      - run: npm run test:stage8-2G-D-A
      - run: npm run test:stage8-2G-D-A-1
      - run: npm run test:stage8-2G-D-A-1a
      - run: npm run test:stage8-2G-D-B
      - run: npm run test:stage8-2G-D-B-1
      - run: npm run test:stage8-2G-D-B-1a
      - run: npm run test:stage8-2G-D-C
      - run: npm run test:stage8-2G-E-A
      - run: npm run test:stage8-2G-E-A-1
      - run: npm run browser:stage8-2G-E-A-1
      - run: npm run test:stage8-2G-E-B
      - run: npm run browser:stage8-2G-E-B
      - run: npm run test:stage8-2G-E-C
      - run: npm run browser:stage8-2G-E-C
      - run: npm run test:stage9-A
      - run: npm run browser:stage9-A
      - run: npm run test:stage9-B
      - run: npm run browser:stage9-B
      - run: npm run test:stage9-C
      - run: npm run browser:stage9-C
